import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import React, { useState, MouseEvent } from "react";
import { fuelStatistic, FuelType, regions, fuelArr } from "../type.ts";
import { faStar, faWarning } from "@fortawesome/free-solid-svg-icons";
import "react-dropdown/style.css";
import { MyDropDown } from "./MyDropDown.tsx";
import { PersonalInfo, Plan, Process, Town } from "../svg";

export function InitialScreen() {
  const [distance, setDistance] = useState<number>(0);
  const [region, setRegion] = useState("");
  const [fuel, setFuel] = useState("");
  const [errorMsg, setErrorMsg] = useState("");
  const [showResult, setShowResult] = useState(false);

  const onShowReult = (e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    if (!distance && !fuel && !region) {
      setErrorMsg("You need to fill in all fields");
      return;
    }
    if (distance < 0) {
      setErrorMsg("Distance can't be negative");
      return;
    }
    setErrorMsg("");
    setShowResult(!showResult);
  };

  return (
    <>
      <div className="intro-container">
        <div className="intro-text">
          <h1>Sustainability week 2022</h1>

          <p>
            Are you curious about how much co2 emission that is generated by
            traveling?
          </p>
          <p>
            Input a distance for example between your home and work and which
            type of fuel/vehicle you used to get to work. If you are curious,
            you can try any other destinations.
          </p>

          <p>
            <b>Note:</b> the data you enter wll not be saved anywehere by any
            mean
          </p>
        </div>
        <div className="intro-image">
          <img src={Town} alt="header" />
        </div>
      </div>
      <div className="initial-container">
        <div className="initial-upper">
          <h3 className="initial-header">Calculate your emission</h3>
          <div className="initial-inputs">
            <div className="input">
              <label>{"How far do you travel (km)*"} </label>
              <input
                type="number"
                value={distance === 0 ? "" : distance}
                onChange={(e) => {
                  setDistance(Number(e.target.value));
                }}
                readOnly={showResult}
              />
            </div>

            <div className="input">
              <label>Where do you travel* </label>
              <MyDropDown
                options={regions}
                value={region}
                onChange={setRegion}
                clickable={!showResult}
              />
            </div>

            <div className="input">
              <label>How do you travel* </label>
              <MyDropDown
                options={fuelStatistic.map((f: FuelType) => f.fuel)}
                value={fuel}
                onChange={setFuel}
                clickable={!showResult}
              />
            </div>
          </div>

          {errorMsg && (
            <>
              <p className="error">
                <FontAwesomeIcon icon={faWarning} /> {errorMsg}
              </p>
            </>
          )}
        </div>

        <button className="button initial-button" onClick={onShowReult}>
          {showResult ? "Edit" : "Show my result"}
        </button>
      </div>
      {showResult && (
        <div className="result-container">
          <div className="result-upper">
            <div className="result-image">
              <img src={Plan} alt="header" />
              {/* <img src={PersonalInfo} alt="header" /> */}
              {/* <img src={Process} alt="header" /> */}
            </div>
            <div className="result-text">
              <h2 className="result-text-title">Your results are:</h2>
              <p className="result-content">
                Your carbon dioxide emission is:{" "}
                <b>{fuelArr[fuel] * distance} g</b>
              </p>

              {distance * fuelArr[fuel] === 0 ? (
                <div>
                  <FontAwesomeIcon
                    icon={faStar}
                    size="5x"
                    beatFade
                    color="#ffde00"
                  />
                </div>
              ) : (
                <div className="result-numbers">
                  <h6>That is eqviallent to...</h6>
                  <p>
                    charging{" "}
                    <b>
                      {Math.round((fuelArr[fuel] * distance * 122) / 1000)}{" "}
                    </b>
                    smart phones
                  </p>
                  <p>
                    switching{" "}
                    <b>{Math.round(fuelArr[fuel] * distance * 0.017 * 38)} </b>
                    incandescent lamps to LEDS
                  </p>
                  <p>
                    emissions captured by a tree seedling grown for{" "}
                    <b>
                      {Math.round(
                        ((fuelArr[fuel] * distance * 0.017) / 1000) * 3650
                      )}{" "}
                    </b>
                    days
                  </p>
                </div>
              )}
            </div>
          </div>
          <p className="link">
            *Want to know more about CO2 equivalencies? Check{" "}
            <a
              href="https://www.epa.gov/energy/greenhouse-gas-equivalencies-calculator#results"
              target="_blank"
              rel="noreferrer"
            >
              here
            </a>
          </p>
          <h1 className="result-tip-header">Do you know that?</h1>
          <div className="tips">
            <div className="tip">
              <p>Car driving</p>
              <div>
                You can save 50% of carbon emissions per person if there are two
                people in a car.
              </div>
            </div>
            <div className="tip">
              <p>Public transport</p>
              <div>
                You can save 75% of emissions by taking the train instead of the
                car traveling the same distance
              </div>
            </div>
            <div className="tip">
              <p>Biking</p>
              <div>
                By biking you loose 0,33 calories per kg body weight per km
              </div>
            </div>
            <div className="tip">
              <p>Car driving</p>
              <div>
                You can save up to 90% of emissions if you drive in an electric
                car compared to a benzin car. It would be 100% if the
                electricity came from renewable energy.
              </div>
            </div>
            <div className="tip">
              <p>Public transport</p>
              <div>
                You save up to 85 % of emissions by taking the bus instead of
                the car?
              </div>
            </div>
            <div className="tip">
              <p>Biking</p>
              <div>
                If you included the impact of the production and maintenance of
                a bike you would emit 21 g CO2 per km? This is still 85% less
                than taking the car.
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
