import React, { Dispatch, SetStateAction } from "react";

interface Props {
  onHide: Dispatch<SetStateAction<boolean>>;
}

export function Intro(props: Props) {
  return (
    <div className="intro_container">
      <p>
        In this time of the year we in sustainable expert group in IST wants to
        provide you more environment related tips to help you to live a more
        sustainable life. Today our foucs is - traveling.
      </p>
      <p>
        Traveling happens everyday in our life, we travel to work, home,
        restaurants glossery stores, hobby spots, pick up the kids...
      </p>
      <p>
        Are you curious about how much co2 emission that is generated by
        traveling?
      </p>
      <p>
        In today's activity we'd like to provid you some breif information of
        some of the mainstream traveling methods' co2 emission, and a little bit
        of tips to help you to travel more environmental friendly in other
        occasions.
      </p>
      <p>
        We use the distance between your home and work as an exmple this time,
        but if you are curious, you can try any other destinations
      </p>
      <p>Note: the data you enter wll not be saved anywehere by any mean</p>

      <button
        className="button intro_button"
        onClick={() => props.onHide(false)}
      >
        OK, I see
      </button>
    </div>
  );
}
